version: '3'

services:
  dev-postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=books
    volumes:
      - pgdata:/var/lib/postgresql/data
  library-app:
    build: .
    ports:
      - 5000:5000

volumes:
  pgdata: